#!/usr/bin/env python3
"""
run_sphere_radial.py -- Randers-UMAP on a synthetic sphere point cloud + a
RADIAL Randers field, using the EXACT SAME pipeline as run_swiss_roll.py /
run_mammoth.py / run_sphere_tangential.py (run_located_drift, imported
directly; make_sphere_points, imported from run_sphere_tangential.py --
only the drift field construction differs between the two sphere scripts).

Radial field
------------
omega_i is the outward unit normal direction at x_i, scaled to
||omega_i|| = alpha everywhere (same constant magnitude as the tangential
field, so direction TYPE is the only variable being compared):

    omega_i = alpha * x_i / ||x_i||

[OURS 2026-08-19] Why this is expected to behave very differently from
run_sphere_tangential.py's field, and why that is the point of having both
scripts: the Randers/asymmetric-geodesic mechanism (both randers_bridge's
compute_dist_matrix and, more generally, the whole "drift perturbs
distance via <omega_i, x_j-x_i>" idea) is only sensitive to the component
of omega_i that is ALIGNED with the displacement to a nearby neighbour,
x_j - x_i. For two points close together on a sphere's surface, x_j - x_i
is dominantly TANGENTIAL to the sphere (to first order in ||x_j-x_i||,
exactly tangential; the curvature-induced radial component is second
order, O(||x_j-x_i||^2 / radius)). A purely radial omega_i is by
construction ORTHOGONAL to the tangent plane, hence nearly orthogonal to
x_j - x_i for every near neighbour -- so <omega_i, x_j-x_i> ~ 0 and the
resulting D_asym should show only a weak, curvature-driven asymmetry
signal, not a clean directional one.

This makes the radial field a useful "negative control": if the pipeline
(locate step, recovered B, direction_accuracy-style validation) correctly
reflects the underlying geometry, run_sphere_radial.py's recovered drift
should correlate much more weakly with the true field than
run_sphere_tangential.py's does, even though both fields have identical
||omega_i|| everywhere and were generated by an otherwise-identical
pipeline. A strong signal here instead would suggest the pipeline (or the
compute_dist_matrix injection) is picking up something other than the
intended tangential-alignment mechanism.

Usage
-----
    python run_sphere_radial.py
    python run_sphere_radial.py --n 2000 --epochs 500
"""

import argparse
import sys
from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from run_swiss_roll import run_located_drift
from run_sphere_tangential import make_sphere_points


def make_sphere_radial_randers(n, seed=42, radius=10.0, alpha=0.5):
    """
    Sphere point cloud + the radial (outward-normal) Randers field
    described in the module docstring.

    Returns
    -------
    X     : (n,3) ambient points
    omega : (n,3) Randers drift vectors, ||omega_i|| == alpha (constant --
            same magnitude convention as run_sphere_tangential.py, so the
            two scripts differ ONLY in direction type)
    theta : (n,) colatitude -- used purely for colouring plots
    """
    X, theta, phi = make_sphere_points(n, seed=seed, radius=radius)

    radial = X / np.linalg.norm(X, axis=1, keepdims=True)
    omega = radial * alpha

    return X, omega, theta


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--n",      type=int, default=1000)
    p.add_argument("--radius", type=float, default=10.0)
    p.add_argument("--k",      type=int, default=20, help="k-NN for the geodesic backbone")
    p.add_argument("--emb-k",  type=int, default=20, help="n_neighbors for randers_umap_fit")
    p.add_argument("--neg",    type=int, default=10)
    p.add_argument("--epochs", type=int, default=500)
    p.add_argument("--locate-epochs", type=int, default=500,
                    help="no-op -- locate step is a single deterministic placement call, no "
                         "training. Kept for compat with run_swiss_roll.py's run_located_drift signature.")
    p.add_argument("--clip-delta", type=float, default=0.01)
    p.add_argument("--gravity", action="store_true",
                    help="[OURS 2026-08-17] add per-node gravity toward xi_i=y_i+b_i "
                         "(Bannister et al. f_g=gamma*M[i]*b_i).")
    p.add_argument("--gravity-strength", type=float, default=1.0)
    p.add_argument("--no-gravity-neighbor-weight", action="store_true")
    p.add_argument("--no-virtual-neighbor", action="store_true",
                    help="[OURS 2026-08-20, default ON] each node's own virtual point "
                         "xi_i=y_i+b_i is, BY DEFAULT, an unconditional (k+1)-th attractive "
                         "neighbour, pulled with UMAP's own attraction curve -- see "
                         "run_swiss_roll.py's --no-virtual-neighbor help for the full "
                         "explanation. Pass this flag to DISABLE it.")
    p.add_argument("--snapshot-every", type=int, default=None)
    p.add_argument("--ramp", action="store_true")
    p.add_argument("--init-only", action="store_true")
    p.add_argument("--init-method", choices=["umap", "isomap"], default="isomap",
                    help="locate step's placement method. 'isomap' (default) = classical_mds. "
                         "'umap' = fuzzy_simplicial_set+spectral_layout.")
    p.add_argument("--alpha", type=float, default=0.5, help="||omega|| for the radial drift field (constant)")
    p.add_argument("--seed",   type=int, default=0)
    p.add_argument("--out",    default="sphere_radial_embedding")
    p.add_argument("--quiet",  action="store_true")
    args = p.parse_args()

    if not args.quiet:
        print(f"Generating sphere (radial field): n={args.n}, radius={args.radius}")
    X, omega, theta = make_sphere_radial_randers(args.n, seed=42, radius=args.radius, alpha=args.alpha)
    n = args.n

    # ---- 3D plot of the ambient sphere with the omega (Randers) field -------
    fig3d = plt.figure(figsize=(11, 9))
    ax3d = fig3d.add_subplot(111, projection="3d")
    sc3d = ax3d.scatter(X[:, 0], X[:, 1], X[:, 2], c=theta, cmap="viridis", s=8,
                        alpha=0.85, linewidths=0)
    fig3d.colorbar(sc3d, ax=ax3d, label="theta (colatitude, 0=north pole)", shrink=0.6, pad=0.08)
    rng3d = np.random.RandomState(0)
    idx3d = rng3d.choice(n, size=min(200, n), replace=False)
    span = X.max(axis=0) - X.min(axis=0)
    omega_norm_max = np.linalg.norm(omega, axis=1).max()
    scale3d = 0.35 * span.max() / max(omega_norm_max, 1e-12)
    ax3d.quiver(X[idx3d, 0], X[idx3d, 1], X[idx3d, 2],
                omega[idx3d, 0] * scale3d, omega[idx3d, 1] * scale3d, omega[idx3d, 2] * scale3d,
                color="k", alpha=0.7, linewidth=1.0, arrow_length_ratio=0.3)
    ax3d.set_title(f"Sphere, RADIAL field (ambient X, n={n}, radius={args.radius})", fontsize=11)
    ax3d.set_xlabel("x"); ax3d.set_ylabel("y"); ax3d.set_zlabel("z")
    fig3d.tight_layout()
    fig3d.savefig(f"{args.out}_3d_field.png", dpi=150)
    if not args.quiet:
        print(f"wrote {args.out}_3d_field.png")

    # ---- 3D plot of the initial data with the drift ATTACHED (x_i -> x_i+omega_i), ----
    # ---- exaggerated to be visible, drawn as crimson quiver arrows -- same -----
    # ---- convention as run_sphere_tangential.py / run_mammoth.py. --------------
    X_virtual_display = X + omega * scale3d
    fig3d_v = plt.figure(figsize=(11, 9))
    ax3d_v = fig3d_v.add_subplot(111, projection="3d")
    sc3d_v = ax3d_v.scatter(X[:, 0], X[:, 1], X[:, 2], c=theta, cmap="viridis", s=8,
                             alpha=0.85, linewidths=0)
    fig3d_v.colorbar(sc3d_v, ax=ax3d_v, label="theta (colatitude, 0=north pole)", shrink=0.6, pad=0.08)
    ax3d_v.quiver(X[idx3d, 0], X[idx3d, 1], X[idx3d, 2],
                  X_virtual_display[idx3d, 0] - X[idx3d, 0],
                  X_virtual_display[idx3d, 1] - X[idx3d, 1],
                  X_virtual_display[idx3d, 2] - X[idx3d, 2],
                  color="crimson", alpha=0.9, linewidth=1.2, arrow_length_ratio=0.25)
    ax3d_v.set_title(f"Sphere, RADIAL: drift attached (x_i -> x_i+omega_i) "
                      f"(n={n}, omega exaggerated x{scale3d:.1f} for visibility)", fontsize=10)
    ax3d_v.set_xlabel("x"); ax3d_v.set_ylabel("y"); ax3d_v.set_zlabel("z")
    fig3d_v.tight_layout()
    fig3d_v.savefig(f"{args.out}_3d_drift_attached.png", dpi=150)
    if not args.quiet:
        print(f"wrote {args.out}_3d_drift_attached.png")

    result = run_located_drift(X, omega, k=args.k, emb_k=args.emb_k, neg=args.neg,
                               locate_epochs=args.locate_epochs, epochs=args.epochs,
                               clip_delta=args.clip_delta, use_gravity=args.gravity,
                               gravity_strength=args.gravity_strength,
                               gravity_neighbor_weight=not args.no_gravity_neighbor_weight,
                               use_virtual_neighbor=not args.no_virtual_neighbor,
                               snapshot_every=args.snapshot_every, ramp=args.ramp,
                               seed=args.seed, verbose=not args.quiet,
                               apply_step=not args.init_only, init_method=args.init_method)
    Y, B = result["Y"], result["B"]

    # ---- plot ------------------------------------------------------------
    fig, ax = plt.subplots(figsize=(9, 8))
    sc = ax.scatter(Y[:, 0], Y[:, 1], c=theta, cmap="viridis", s=10, alpha=0.85, linewidths=0)
    plt.colorbar(sc, ax=ax, label="theta (colatitude)")

    bn = np.linalg.norm(B, axis=1)
    big = np.argsort(bn)[::-1][:200]
    if bn.max() > 0:
        sc_scale = 0.12 * (Y.max() - Y.min()) / bn.max()
        ax.quiver(Y[big, 0], Y[big, 1], B[big, 0] * sc_scale, B[big, 1] * sc_scale,
                  color="k", alpha=0.6, width=0.004, scale=1, scale_units="xy")

    ax.set_xticks([]); ax.set_yticks([])
    if args.init_only:
        ax.set_title(f"Randers-UMAP sphere (radial), LOCATED INIT ONLY ({args.init_method}, no training)  (n={n})", fontsize=11)
    else:
        ax.set_title(f"Randers-UMAP sphere (radial), located-drift init ({args.init_method})  (n={n})", fontsize=11)
    fig.tight_layout()
    fig.savefig(f"{args.out}.png", dpi=150)

    np.savez(f"{args.out}.npz", Y=Y, B=B, theta=theta, X=X, omega=omega)

    if not args.quiet:
        print(f"\nwrote {args.out}.png and {args.out}.npz")

    # ---- snapshot grid: init -> every N epochs -> final, side by side -------
    if args.snapshot_every is not None and not args.init_only:
        snaps = result["snapshots"]
        n_snap = len(snaps)
        ncols = min(n_snap, 6)
        nrows = int(np.ceil(n_snap / ncols))
        fig2, axes = plt.subplots(nrows, ncols, figsize=(3.2 * ncols, 3.2 * nrows),
                                   squeeze=False)
        vmin, vmax = theta.min(), theta.max()
        sc2 = None
        for idx, snap in enumerate(snaps):
            ax2 = axes[idx // ncols][idx % ncols]
            Yi = snap["Y"]
            Bi = snap["B"]
            sc2 = ax2.scatter(Yi[:, 0], Yi[:, 1], c=theta, cmap="viridis", s=6,
                              alpha=0.85, linewidths=0, vmin=vmin, vmax=vmax)
            bni = np.linalg.norm(Bi, axis=1)
            bigi = np.argsort(bni)[::-1][:200]
            if bni.max() > 0:
                sc_scale_i = 0.12 * (Yi.max() - Yi.min()) / bni.max()
                ax2.quiver(Yi[bigi, 0], Yi[bigi, 1],
                          Bi[bigi, 0] * sc_scale_i, Bi[bigi, 1] * sc_scale_i,
                          color="k", alpha=0.6, width=0.006, scale=1, scale_units="xy")
            ax2.set_title(f"epoch {snap['epoch']}", fontsize=9)
            ax2.set_xticks([]); ax2.set_yticks([])
        for idx in range(n_snap, nrows * ncols):
            axes[idx // ncols][idx % ncols].axis("off")
        fig2.suptitle(f"Randers-UMAP sphere (radial), apply-step trajectory  (n={n}, "
                      f"snapshot_every={args.snapshot_every})", fontsize=11)
        if sc2 is not None:
            fig2.colorbar(sc2, ax=axes, label="theta (colatitude)",
                          fraction=0.02, pad=0.01)
        fig2.savefig(f"{args.out}_snapshots.png", dpi=150, bbox_inches="tight")

        if not args.quiet:
            print(f"wrote {args.out}_snapshots.png ({n_snap} snapshots)")


if __name__ == "__main__":
    main()
